export function backIn(time: number, overshoot?: number | undefined): number;
export function backOut(time: number, overshoot?: number | undefined): number;
export function backInOut(time: number, overshoot?: number | undefined): number;
export function bounceOut(time: number): number;
export function bounceIn(time: number): number;
export function bounceInOut(time: number): number;
export function circIn(time: number): number;
export function circOut(time: number): number;
export function circInOut(time: number): number;
export function cubicIn(time: number): number;
export function cubicOut(time: number): number;
export function cubicInOut(time: number): number;
export function elasticOut(time: number, amplitude?: number | undefined, period?: number | undefined): number;
export function elasticIn(time: number, amplitude?: number | undefined, period?: number | undefined): number;
export function elasticInOut(time: number, amplitude?: number | undefined, period?: number | undefined): number;
export function expoIn(time: number): number;
export function expoOut(time: number): number;
export function expoInOut(time: number): number;
export function linear(time: number): number;
export function quadIn(time: number): number;
export function quadOut(time: number): number;
export function quadInOut(time: number): number;
export function quartIn(time: number): number;
export function quartOut(time: number): number;
export function quartInOut(time: number): number;
export function quintIn(time: number): number;
export function quintOut(time: number): number;
export function quintInOut(time: number): number;
export function sineIn(time: number): number;
export function sineOut(time: number): number;
export function sineInOut(time: number): number;
export function inOut(time: number, start: EasingFunction, end: EasingFunction): number;
export type EasingFunction = (time: number) => number;
